### PR TITLE
MVP setup of Weights & Biases

### PR DESCRIPTION
**Pull request by rusheb**
## Changes
- Install the package
- Add a new script that uploads artifacts to the w&b project

Artifacts can be viewed at the [w&b dashboard](https://wandb.ai/aisc-search/understanding-search/artifacts) once you have been added to the project. Team members can tell me their preferred email address for access on this [Slack thread](https://searchingforsearch.slack.com/archives/C04QRDD81LZ/p1678865774953109).

## Notes
- I want to add setup instructions to the readme, but I'm not sure what will be required. Please can somebody try to run the new script and tell me the steps they had to take? I expect it will be this:
    ```bash
    pipenv install --sync
    wandb login
    ```
- Should I add an integration test? E.g. something that generates a small dataset and uploads it as an artifact
- What else do we want to do with this (in subsequent tickets)?
  - Log all training runs?
  - Add maze images into the training run logs
  - Log evaluations?
  - Load dataset from w&b?
  - What else?

### CODE REVIEW

**Comment by valedan** [comment]
> pipenv install --sync

Do you mean `poetry install --with-dev`??

**Comment by valedan** [comment]
Script worked for me! https://wandb.ai/aisc-search/understanding-search/artifacts/dataset/g4-n11/v0

**Comment by valedan** [comment]
> Should I add an integration test? E.g. something that generates a small dataset and uploads it as an artifact

I don't have a strong opinion on whether this is worth the time to implement or not (I definitely think it's not essential) - but if you do go ahead with this make sure that they get uploaded to a `/testing` folder or something to avoid cluttering up wandb.

**Review by valedan — APPROVED** [review]
Looks great!

**Comment by rusheb** [comment]
> > pipenv install --sync
> 
> Do you mean `poetry install --with-dev`??

Haha, sorry, I meant `poetry install --sync`. The `--sync` flag probably isn't necessary though.

Thanks for running it! What are the exact steps you took?

**Pull request merged**
