### PR TITLE
73 - Fix coordinates in plot_maze

### LINKED ISSUE #73: Use consistent coordinate system
I've been getting really confused by the different coordinate systems used for different maze representations

* The LatticeMaze connection_list, adjlist and as_img use (x is rows) with origin at top left
* the path produced by plot_path uses (x is columns)  with origin at top left (meaning we have to transpose the image to plot them together
* the path produced by plot_multi_paths uses (x is columns) with origin at bottom left!! 

We should pick a convention and stick to it. to minimise the amount of changes we need to make, I think we should use
* Origin at top left
* x is rows is down
* y is columns is right

### PR DESCRIPTION
**Pull request by valedan**
I believe this resolves #73 

The issue was that in our generation and tokenization code we are using array notation for all coordinates - (row, col). But matplotlib uses Cartesian coordinates - (x, y). These are opposites, which caused a lot of confusion in `plot_maze.py` where we are plotting mazes and paths.

There are 2 fixes here:
- Swap the dimensions of the path coordinates when we plot them in matplotlib
- Fix usage of `extent` which was causing origin to appear at the bottom instead of the top.

**Note**: I don't have any tests for this yet. Both of these functions are just rendering plots so unit tests are a bit of a pain. I'll have to extract out all the logic involved in calculating the inputs for `plt.plot`  into seperate functions and test those. Putting the PR up now so I can get a sanity check on the actual fix while I work on tests and refactoring.

Plots after fix:

Screenshot 2023-03-13 at 3 37 52 PM
Screenshot 2023-03-13 at 4 01 03 PM

### CODE REVIEW

**Comment by rusheb** [comment]
Amazing work!

**Comment by afspies** [comment]
Looks good - for my own clarity, we are using (x<->columns, y<->rows) with (0,0) at the top?

Is this the same coordinate system as in the tokenization (i.e. (0,0)<->(0,1) => a connection from the top left to the cell underneath?

**Review by afspies — COMMENTED** [review]
Looks good - for my own clarity, we are using (x<->columns, y<->rows) with (0,0) at the top left?

Is this the same coordinate system as in the tokenization (i.e. (0,0)<->(0,1) => a connection from the top left to the cell underneath?

**Review by mivanit — APPROVED** [review]
LGTM! this is also much cleaner than the cursed `rot90` haha

**Comment by valedan** [comment]
> Looks good - for my own clarity, we are using (x<->columns, y<->rows) with (0,0) at the top left?

Yep!

> Is this the same coordinate system as in the tokenization (i.e. (0,0)<->(0,1) => a connection from the top left to the cell underneath?

In the tokenization we use (rows, cols), so (0,0)<->(0,1) is a connection from top left to the cell on the right (ie 1 col over).

But [plt.plot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html) uses Cartesian (x, y) coordinates, so (0,0)<->(0,1) is a connection from top left to the cell underneath (moving down the y-axis). 

So when plotting mazes, we need to swap the coordinate dimensions when passing coordinate tokens into `plt.plot`.

**Comment by rusheb** [comment]
> > Looks good - for my own clarity, we are using (x<->columns, y<->rows) with (0,0) at the top left?
> 
> Yep!

Oh! I'm confused by this. I think we want to use (x<->rows, y<-> columns), so the visualization maps to the connection list

e.g. 
```
[
  [[T, T],
   [F, F]],
  [[T, F],
   [F, F]]
]
```

will be plotted like 
```
N - N
|   | 
N   N
```


That's what we are doing right?

**Comment by valedan** [comment]
@rusheb I just tested it out, and for the connection list you provided the plot is:

Screenshot 2023-03-14 at 9 01 19 AM

**Comment by rusheb** [comment]
okay perfect! so x is rows, not columns. right? or am I still mixed up?

**Comment by valedan** [comment]
Ah okay this is a little confusing! When we do `plt.imshow(img` we leave `img` in (row, col) format because `imshow` handles that fine. Everything I said above about swapping dimensions only applies to the `path` coordinates that we pass into `plt.plot`

**Review by afspies — APPROVED** [review]
LGTM!

**Pull request merged**
